---
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff via poetry
        entry: poetry run ruff check
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format via poetry
        entry: poetry run ruff format
        language: system
        types: [python]
