# Generated by Django 5.2.6 on 2025-10-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='to_delete',
            field=models.BooleanField(default=0),
        ),
    ]
