---
# This compose-file should not be called directly!
#
# Instead, it should be applied over docker-compose.yml
#  and docker-compose.prod.yml

services:
  caddy:
    volumes:
      - ./docker/caddy/Caddyfile.dev:/etc/caddy/Caddyfile
    ports: !override
      - "8000:8000"
