# Generated by Django 5.2.6 on 2025-11-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TgUserState',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('chat_id', models.BigIntegerField(default=0)),
                ('user_id', models.BigIntegerField()),
                (
                    'state',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=254,
                    ),
                ),
                ('state_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
