# Generated by Django 5.2.6 on 2025-09-14 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'password',
                    models.CharField(max_length=128, verbose_name='password'),
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        help_text='Enter your email: ',
                        max_length=256,
                        unique=True,
                        verbose_name='Email',
                    ),
                ),
                (
                    'full_name',
                    models.CharField(
                        default='Unknown',
                        help_text='Enter your full name: ',
                        max_length=256,
                        verbose_name='Full name',
                    ),
                ),
                (
                    'position',
                    models.CharField(
                        blank=True,
                        help_text='Enter your possition: ',
                        max_length=128,
                        verbose_name='Position',
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        blank=True,
                        help_text='Enter your role: ',
                        max_length=128,
                        verbose_name='Role',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True, verbose_name='Active status'
                    ),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=True, verbose_name='Staff status'
                    ),
                ),
                (
                    'tg_id',
                    models.PositiveBigIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name='Telegram id',
                    ),
                ),
                (
                    'edited_at',
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name='Время редактирования',
                    ),
                ),
                (
                    'department',
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the user's department (optional): ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='users',
                        to='company.department',
                    ),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('email', 'full_name'),
                'default_related_name': 'users',
            },
        ),
    ]
