# Generated by Django 5.2.6 on 2025-09-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={
                'default_related_name': 'users',
                'ordering': ('email', 'full_name'),
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='edited_at',
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name='Время редактирования'
            ),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(
                default='Unknown',
                help_text='Enter your full name: ',
                max_length=256,
                verbose_name='Full name',
            ),
        ),
    ]
