# Generated by Django 5.2.5 on 2025-09-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tg_id',
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name='Telegram id'
            ),
        ),
    ]
