# Generated by Django 5.2.6 on 2025-09-24 15:43

import django.core.validators
from django.db import migrations, models

import server.apps.users.validators


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tg_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tg_username',
            field=models.CharField(
                blank=True,
                help_text='Enter your telegram @username: ',
                max_length=33,
                validators=[
                    server.apps.users.validators.validate_telegram_username,
                    django.core.validators.MinLengthValidator(6),
                ],
                verbose_name='Telegram username',
            ),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(
                condition=models.Q(('tg_username', ''), _negated=True),
                fields=('tg_username',),
                name='unique_tg_username_not_blank',
            ),
        ),
    ]
