# Generated by Django 5.2.6 on 2025-10-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0002_initial'),
        (
            'users',
            '0002_remove_customuser_tg_id_customuser_tg_username_and_more',
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(
                condition=models.Q(('email', ''), _negated=True),
                fields=('email',),
                name='unique_email',
            ),
        ),
    ]
