# Generated by Django 5.2.6 on 2025-10-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_customuser_unique_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='to_inactivate',
            field=models.BooleanField(
                default=False, verbose_name='Inactivated soon'
            ),
        ),
    ]
