# Generated by Django 5.2.6 on 2025-09-17 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField()),
                (
                    'question_type',
                    models.CharField(
                        choices=[
                            ('ratingScale', 'Rating scale'),
                            ('score', 'Score'),
                            ('consentGiven', 'Consent given'),
                        ],
                        max_length=254,
                    ),
                ),
                ('is_favorite', models.BooleanField(default=False)),
            ],
            options={
                'default_related_name': 'questions',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text_answer', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'user answer',
                'verbose_name_plural': 'user answers',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                (
                    'question',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='surveys.question',
                    ),
                ),
            ],
            options={
                'verbose_name': 'answer option',
                'default_related_name': 'answer_options',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                (
                    'department',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='surveys',
                        to='company.department',
                    ),
                ),
            ],
            options={
                'default_related_name': 'surveys',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='surveys.survey'
            ),
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'survey',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='result',
                        to='surveys.survey',
                    ),
                ),
            ],
            options={
                'verbose_name': 'survey result',
                'verbose_name_plural': 'survey results',
            },
        ),
    ]
