# Generated by Django 5.2.6 on 2025-09-18 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'default_related_name': 'questions', 'ordering': ('id',)},
        ),
    ]
