# Generated by Django 5.2.6 on 2025-09-17 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='survey_result',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_answers',
                to='surveys.question',
            ),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_options',
            field=models.ManyToManyField(
                blank=True,
                related_name='user_answers',
                to='surveys.answeroption',
            ),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='survey_result',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_answers',
                to='surveys.surveyresult',
            ),
        ),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(
                fields=('question', 'text'), name='unique_answer'
            ),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('end_date__gte', models.F('start_date')),
                    ('end_date__isnull', True),
                    _connector='OR',
                ),
                name='surveys_survey_dates_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(
                fields=('survey', 'text'), name='unique_question_per_survey'
            ),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'question_type__in',
                    ['ratingScale', 'score', 'consentGiven'],
                )),
                name='surveys_question_question_type_valid',
            ),
        ),
    ]
