# Generated by Django 5.2.6 on 2025-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0002_initial'),
        ('surveys', '0002_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('active', 'Active'),
                    ('completed', 'Completed'),
                ],
                default='draft',
                max_length=254,
            ),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'status__in',
                    ['draft', 'active', 'completed'],
                )),
                name='surveys_survey_status_valid',
            ),
        ),
    ]
