# Generated by Django 5.2.6 on 2025-09-17 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'default_related_name': 'questions', 'ordering': ('id',)},
        ),
    ]
