# Generated by Django 5.2.6 on 2025-09-25 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0003_survey_status_survey_surveys_survey_status_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='current_question',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='surveys.question',
            ),
        ),
    ]
