# Generated by Django 5.2.6 on 2025-09-27 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0004_surveyresult_current_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_question_per_survey',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='question',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='surveys.question',
            ),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='surveys.survey'
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='surveys',
            field=models.ManyToManyField(
                related_name='questions',
                through='surveys.SurveyQuestion',
                to='surveys.survey',
            ),
        ),
        migrations.AddConstraint(
            model_name='surveyquestion',
            constraint=models.UniqueConstraint(
                fields=('survey', 'question'), name='unique_survey_question'
            ),
        ),
    ]
