# Generated by Django 5.2.6 on 2025-10-04 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0005_surveyquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='completed_questions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
