# Generated by Django 5.2.6 on 2025-10-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0006_surveyresult_completed_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
