# Generated by Django 5.2.6 on 2025-10-06 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0006_surveyresult_completed_questions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StatisticSettings',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'survey_response_avg_period',
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text='How many latest surveys are taken into account while calculating the question response average time for the user.',
                    ),
                ),
                (
                    'singleton',
                    models.BooleanField(default=True, editable=False),
                ),
            ],
            options={
                'verbose_name': 'statistics settings',
                'verbose_name_plural': 'statistics settings',
                'default_related_name': 'stat_settings',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('singleton',), name='single_instance_constraint'
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'average_answer_sec',
                    models.PositiveIntegerField(default=0),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'user statistics',
                'verbose_name_plural': 'user statistics',
                'default_related_name': 'statistics',
            },
        ),
    ]
