# Generated by Django 5.2.6 on 2025-10-07 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0007_alter_surveyresult_started_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='bot_state',
            field=models.CharField(
                choices=[
                    ('waitingStart', 'Waiting start'),
                    ('inSurvey', 'In survey'),
                    ('completed', 'Completed'),
                    ('editing', 'Editing'),
                ],
                default='waitingStart',
                max_length=254,
            ),
        ),
        migrations.AddConstraint(
            model_name='surveyresult',
            constraint=models.CheckConstraint(
                condition=models.Q((
                    'bot_state__in',
                    ['waitingStart', 'inSurvey', 'completed', 'editing'],
                )),
                name='surveys_surveyresult_bot_state_valid',
            ),
        ),
    ]
