# Generated by Django 5.2.6 on 2025-10-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0010_remove_survey_surveys_survey_status_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='to_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='to_delete',
            field=models.BooleanField(default=0),
        ),
    ]
